language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - qtbase5-dev
            - qttools5-dev
            - liblua5.2-dev
            - libcairo2-dev
            - libpango1.0-dev
            - libboost-all-dev
            - libqt5svg5-dev
            - libgtest-dev
            - libeigen3-dev
            - libcurl4-gnutls-dev
            - libgtk-3-dev
            - libgdk-pixbuf2.0-dev
            - gcc-4.9
            - g++-4.9
            - clang-6.0
            - clang-tidy-6.0
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"


cache: ccache

script:
  - ./scripts/travis.sh

#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#librecad"
#    template:
#      - "%{repository_slug} (%{commit}) : %{commit_message} %{result}"
#      - "Build details: %{build_url}"
#    on_success: always
#    on_failure: always
